domd5: fall back to fd read loop on mmap failure
This completes support for building packages with 2G+ files, more or
less (packaging 4G+ files is still a distant goal).  I am able to build
a valid package with a 3G sparse file on both i586 and x86-64.  On i586,
though, such a package cannot be installed with rpm-4.0:

    error: unpacking of archive failed on file /usr/bin/6;5a70a676:
    cpio: write failed - File too large

I believe there is no obvious way to identify and mark such packages,
since rpmlib(LargeFiles) dependency is meant only for 4G+ files, which
require 07070X cpio entries.

Therefore, limited support for handling such packages shall be provided
for rpm-4.0 in branch p8 (there are issues other than simply enabling
AC_SYS_LARGEFILE).